USE [master]
GO
/****** Object:  Database [magia]    Script Date: 19/05/2021 15:12:20 ******/
CREATE DATABASE [magia] ON  PRIMARY 
( NAME = N'magia', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\magia.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'magia_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\magia.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [magia] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [magia].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [magia] SET ANSI_NULL_DEFAULT ON 
GO
ALTER DATABASE [magia] SET ANSI_NULLS ON 
GO
ALTER DATABASE [magia] SET ANSI_PADDING ON 
GO
ALTER DATABASE [magia] SET ANSI_WARNINGS ON 
GO
ALTER DATABASE [magia] SET ARITHABORT ON 
GO
ALTER DATABASE [magia] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [magia] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [magia] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [magia] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [magia] SET CURSOR_DEFAULT  LOCAL 
GO
ALTER DATABASE [magia] SET CONCAT_NULL_YIELDS_NULL ON 
GO
ALTER DATABASE [magia] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [magia] SET QUOTED_IDENTIFIER ON 
GO
ALTER DATABASE [magia] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [magia] SET  DISABLE_BROKER 
GO
ALTER DATABASE [magia] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [magia] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [magia] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [magia] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [magia] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [magia] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [magia] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [magia] SET RECOVERY FULL 
GO
ALTER DATABASE [magia] SET  MULTI_USER 
GO
ALTER DATABASE [magia] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [magia] SET DB_CHAINING OFF 
GO
USE [magia]
GO
/****** Object:  Table [dbo].[usuario]    Script Date: 19/05/2021 15:12:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[usuario](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [nvarchar](50) NOT NULL,
	[apellido] [nvarchar](50) NOT NULL,
	[identificacion] [int] NOT NULL,
	[edad] [int] NOT NULL,
	[casa] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_usuario] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [magia] SET  READ_WRITE 
GO
